#backend:
#  name: test-repo

backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key",   name: "templateKey",  widget: "hidden", default: "blog-post"}
      - {label: "Title",          name: "title",        widget: "string"}
      - {label: "Publish Date",   name: "date",         widget: "datetime"}
      - {label: "Author",         name: "author",       widget: "relation", collection: "authors", searchFields: ["name", "title"], valueField: "title"}
      - {label: "Featured Image", name: "image",        widget: "image"}
      - {label: "Description",    name: "description",  widget: "text"}
      - {label: "Body",           name: "body",         widget: "markdown"}
      - {label: "Tags",           name: "tags",         widget: "list"}
      - {label: "Related Posts",  name: "relatedPosts", widget: "list", fields: [{name: "post", label: "Post", widget: "relation", collection: "blog", searchFields: ["name", "title"], valueField: "title"}]}
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Template Key",   name: "templateKey",  widget: "hidden", default: "portfolio-page"}
      - {label: "Title",          name: "title",        widget: "string"}
      - {label: "Featured Image", name: "image",        widget: "image"}
      - {label: "Description",    name: "description",  widget: "text"}
      - {label: "Featured Post",  name: "featuredPost", widget: "relation", collection: "blog", searchFields: ["name", "title"], valueField: "title"}
      - {label: "Categories",     name: "categories",   widget: "list",     fields: [{name: "category", label: "Category", widget: "relation", collection: "category", searchFields: [name, title], valueField: title}, {label: "Category Image", name: "categoryI  mage", widget: "image"}]}
      - {label: "Top Posts",      name: "relatedPosts", widget: "list",     fields: [{name: "post", label: "Post", widget: "relation", collection: "blog", searchFields: [name, title], valueField: title}]}
  - name: "category"
    label: "Category"
    folder: "src/pages/category"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Template Key",   name: "templateKey",    widget: "hidden", default: "category-page"}
      - {label: "Name",           name: "name",           widget: "string"}
      - {label: "Title",          name: "title",          widget: "string"}
      - {label: "Featured Image", name: "image",          widget: "image"}
      - {label: "Description",    name: "description",    widget: "text"}
      - {label: "Thesis",         name: "thesis",         widget: "list",   fields: [{label: "Headline",  name: "headline", widget: "string"}, {label: "Highlight", name: "highlighted", widget: "boolean"}, {label: "Body", name: "body", widget: "markdown"}]}
      - {label: "Featured video", name: "video",          widget: "string"}
      - {label: "Success stories",name: "successStories", widget: "list",   fields: [{label: "Post",      name: "post",     widget: "relation", collection: "blog", searchFields: [name, title], valueField: title}, {label: "Name",  name: "customerName", widget: "string"}, {label: "Story Image",  name: "storyImage", widget: "image"}]}
      - {label: "Info Box",       name: "infoBox",        widget: "object", fields: [{label: "Headline",  name: "headline", widget: "string"}, {label: "Body",  name: "body", widget: "markdown"}, {label: "Image",  name: "image", widget: "image"}]}
      - {label: "Statements",     name: "statements",     widget: "list",   fields: [{label: "Image",  name: "image", widget: "image"}, {label: "Name", name: "name", widget: "string"}, {label: "Body", name: "body", widget: "markdown"}]}
      - {label: "Top Posts",      name: "relatedPosts", widget: "list",     fields: [{name: "post", label: "Post", widget: "relation", collection: "blog", searchFields: [name, title], valueField: title}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/jobs/index.md"
        label: "Jobs"
        name: "jobs"
        fields:
          - {label: "Template Key", name: "templateKey",  widget: "hidden", default: "simple-page"}
          - {label: "Title",        name: "title",        widget: "string"}
          - {label: "Body",         name: "body",         widget: "markdown"}
      - file: "src/pages/organisation-innovation/index.md"
        label: "Organisation & Innovation"
        name: "organisation-innovation"
        fields:
          - {label: "Template Key", name: "templateKey",  widget: "hidden", default: "simple-page"}
          - {label: "Title",        name: "title",        widget: "string"}
          - {label: "Body",         name: "body",         widget: "markdown"}
      - file: "src/pages/digitalisierung-arbeitsplatz/index.md"
        label: "Digitalisierung & Arbeitsplatz"
        name: "digitalisierung-arbeitsplatz"
        fields:
          - {label: "Template Key", name: "templateKey",  widget: "hidden", default: "simple-page"}
          - {label: "Title",        name: "title",        widget: "string"}
          - {label: "Body",         name: "body",         widget: "markdown"}
      - file: "src/pages/mitarbeiter-fuehrung/index.md"
        label: "Mitarbeiter & Führung"
        name: "mitarbeiter-fuehrung"
        fields:
          - {label: "Template Key", name: "templateKey",  widget: "hidden", default: "simple-page"}
          - {label: "Title",        name: "title",        widget: "string"}
          - {label: "Body",         name: "body",         widget: "markdown"}
      - file: "src/pages/realexperts-team/index.md"
        label: "Team Real Experts"
        name: "realexperts-team"
        fields:
          - {label: "Template Key", name: "templateKey",  widget: "hidden", default: "simple-page"}
          - {label: "Title",        name: "title",        widget: "string"}
          - {label: "Body",         name: "body",         widget: "markdown"}
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "imprint"
        fields:
          - {label: "Template Key", name: "templateKey",  widget: "hidden", default: "simple-page"}
          - {label: "Title",        name: "title",        widget: "string"}
          - {label: "Body",         name: "body",         widget: "markdown"}
      - file: "src/pages/datenschutz/index.md"
        label: "Datenschutzerklärung"
        name: "dataPrivacy"
        fields:
          - {label: "Template Key", name: "templateKey",  widget: "hidden", default: "simple-page"}
          - {label: "Title",        name: "title",        widget: "string"}
          - {label: "Body",         name: "body",         widget: "markdown"}
      - file: "src/pages/index.md"
        label: "Frontpage"
        name: "frontpage"
        fields:
          - {label: "Template Key",   name: "templateKey",  widget: "hidden", default: "front-page"}
          - {label: "Title",          name: "title",        widget: "string"}
          - {label: "Claim",          name: "claim",        widget: "object", fields: [{label: "Heading",   name: "heading",  widget: "string"}, {label: "Teaser text", name: "teaser", widget: "text"}, {label: "Link to", name: "linkto", widget: "relation", collection: "pages", searchFields: [name, path, title], valueField: "path"}]}
          - {label: "Thesis",         name: "thesis",       widget: "list",   fields: [{label: "Headline",  name: "headline", widget: "string"}, {label: "Highlight", name: "highlighted", widget: "boolean"}, {label: "Body", name: "body", widget: "markdown"}]}
          - {label: "Featured video", name: "video",        widget: "string"}
          - {label: "Top Posts",      name: "relatedPosts", widget: "list",   fields: [{label: "Post",      name: "post",     widget: "relation", collection: "blog", searchFields: [name, title], valueField: title}]}
  - name: "authors"
    label: "Authors"
    editor:
      preview: false
    folder: "src/pages/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key",   name: "templateKey",  widget: "hidden", default: "simple-page"}
      - {label: "Content type",   name: "contentType",  widget: "hidden", default: "author"}
      - {label: "Name",           name: "title",        widget: "string"}
      - {label: "Position",       name: "position",     widget: "string"}
      - {label: "Company",        name: "company",      widget: "string"}
      - {label: "Email",          name: "email",        widget: "string"}
      - {label: "Twitter handle", name: "twitterHandle",widget: "string", required: false}
      - {label: "Profile Image",  name: "image",        widget: "image"}
      - {label: "Description",    name: "description",  widget: "markdown"}
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Settings"
        file: "src/settings/general.json"
        description: "General Site Settings"
        fields:
          - {label: "ID (to query for)", name: "id", widget: "hidden", default: "general-settings"}
          - label: "Global"
            name: "global"
            widget: "object"
            fields:
              - {label: "Title of the website", name: "title", widget: "string"}
              - {label: "URL of the website (https://example.com)", name: "url", widget: "string"}
              - {label: "Default twitter handle (used for social buttons as fallback)", name: "defaultTwitterHandle", widget: "string"}
          - label: "API keys"
            name: "apiKeys"
            widget: "object"
            fields:
              - {label: "Google Maps (https://cloud.google.com/console/google/maps-apis/overview)", name: "googleMaps", widget: "string"}
          - label: "Contact information"
            name: "contactInfo"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown" }
              - {label: "Street & Number", name: "street", widget: "string"}
              - {label: "Zip & City", name: "zip", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Fax", name: "fax", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - label: "Location position"
                name: "location"
                widget: "object"
                fields:
                  - {label: "Latitude", name: "latitude", widget: "number", valueType: "float", min: -90, max: 90}
                  - {label: "Longitude", name: "longitude", widget: "number", valueType: "float", min: -180, max: 180}
          - label: "Posts"
            name: "posts"
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: "frontLimit", widget: "number"}
              - {label: "Default Author", name: "defaultAuthor", widget: "relation", collection: "authors", searchFields: ["title", "position", "company"], valueField: "title"}
  - name: "menu"
    label: "Menu"
    delete: false
    editor:
      preview: false
    files:
      - name: "mainMenuSettings"
        label: "Main menu"
        file: "src/settings/main-menu.json"
        description: "Main menu settings"
        fields:
          - {label: "ID (to query for)", name: "id", widget: "hidden", default: "main-menu-settings"}
          - label: "Main menu"
            name: "mainMenu"
            widget: "list"
            fields:
              - {name: "title", label: "Title", widget: "string"}
              - {name: "url", label: "Url", widget: "string"}
              - {name: "link", label: "Link", widget: "relation", collection: "portfolio", searchFields: ["title"], valueField: "title"}
      - name: "footerLinksSettings"
        label: "Footer links"
        file: "src/settings/footer-links.json"
        description: "Footer links settings"
        fields:
          - {label: "ID (to query for)", name: "id", widget: "hidden", default: "footer-links-settings"}
          - label: "Footer links"
            name: "footerLinks"
            widget: "list"
            fields:
              - {name: "title", label: "Section title", widget: "string"}
              - {name: "links", label: "Links", widget: "list", fields: [{name: "title", label: "Title", widget: "string"},{name: "url", label: "Url", widget: "string"},{name: "link", label: "Link", widget: "relation", collection: "pages", searchFields: ["title"], valueField: "title"}]}
      - name: "footerMenuSettings"
        label: "Footer menu"
        file: "src/settings/footer-menu.json"
        description: "Footer menu settings"
        fields:
          - {label: "ID (to query for)", name: "id", widget: "hidden", default: "footer-menu-settings"}
          - label: "Footer menu"
            name: "footerMenu"
            widget: "list"
            fields:
              - {name: "title", label: "Menu title", widget: "string"}
              - {name: "url", label: "Url", widget: "string"}
              - {name: "link", label: "Link", widget: "relation", collection: "pages", searchFields: ["title"], valueField: "title"}
